# Generated by Django 5.1.1 on 2024-10-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('glutenFree', models.BooleanField(default=False)),
                ('dairy', models.BooleanField(default=False)),
                ('peanuts', models.BooleanField(default=False)),
                ('soybean', models.BooleanField(default=False)),
                ('wheat', models.BooleanField(default=False)),
                ('eggs', models.BooleanField(default=False)),
                ('coconut', models.BooleanField(default=False)),
                ('fish', models.BooleanField(default=False)),
                ('shellfish', models.BooleanField(default=False)),
                ('sesame', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('glutenFree', models.BooleanField(default=False)),
                ('dairy', models.BooleanField(default=False)),
                ('peanuts', models.BooleanField(default=False)),
                ('soybean', models.BooleanField(default=False)),
                ('wheat', models.BooleanField(default=False)),
                ('eggs', models.BooleanField(default=False)),
                ('coconut', models.BooleanField(default=False)),
                ('fish', models.BooleanField(default=False)),
                ('shellfish', models.BooleanField(default=False)),
                ('sesame', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
